import type {
  Achievement,
  Habit,
  Profile,
  Task,
  TaskCategory,
  TaskCompletion,
  XpEvent,
} from "@/lib/types";

const demoUserId = "demo-user";
const today = new Date();
const tomorrow = new Date();
tomorrow.setDate(today.getDate() + 1);
const yesterday = new Date();
yesterday.setDate(today.getDate() - 1);

export const defaultCategories: TaskCategory[] = [
  {
    id: "home-base",
    user_id: null,
    name: "Home Base",
    slug: "home-base",
    description: "House work, repairs, resets, and personal environment.",
    color: "#d6a84f",
    sort_order: 1,
  },
  {
    id: "career-forge",
    user_id: null,
    name: "Career Forge",
    slug: "career-forge",
    description: "Deep work, job growth, portfolio, and professional moves.",
    color: "#9fa86d",
    sort_order: 2,
  },
  {
    id: "body",
    user_id: null,
    name: "Body",
    slug: "body",
    description: "Training, recovery, nutrition, and health maintenance.",
    color: "#b9835a",
    sort_order: 3,
  },
  {
    id: "command-center",
    user_id: null,
    name: "Command Center",
    slug: "command-center",
    description: "Bills, planning, admin, calendar, and logistics.",
    color: "#7f8d74",
    sort_order: 4,
  },
  {
    id: "skills",
    user_id: null,
    name: "Skills",
    slug: "skills",
    description: "Learning, practice, reading, and deliberate improvement.",
    color: "#b6a26d",
    sort_order: 5,
  },
  {
    id: "personal",
    user_id: null,
    name: "Personal",
    slug: "personal",
    description: "Relationships, recovery, errands, and life maintenance.",
    color: "#a87562",
    sort_order: 6,
  },
];

export const defaultAchievements: Achievement[] = [
  {
    id: "first-win",
    code: "first-win",
    name: "First Win",
    description: "Complete your first mission.",
    xp_bonus: 25,
    unlock_kind: "total_completions",
    unlock_threshold: 1,
  },
  {
    id: "ten-count",
    code: "ten-count",
    name: "Ten Count",
    description: "Complete ten missions.",
    xp_bonus: 75,
    unlock_kind: "total_completions",
    unlock_threshold: 10,
  },
  {
    id: "three-day-streak",
    code: "three-day-streak",
    name: "Three-Day Streak",
    description: "Log wins three days in a row.",
    xp_bonus: 100,
    unlock_kind: "current_streak",
    unlock_threshold: 3,
  },
  {
    id: "high-stakes",
    code: "high-stakes",
    name: "High Stakes",
    description: "Complete five critical missions.",
    xp_bonus: 125,
    unlock_kind: "critical_completed",
    unlock_threshold: 5,
  },
  {
    id: "level-keeper",
    code: "level-keeper",
    name: "Level Keeper",
    description: "Earn 1,000 XP.",
    xp_bonus: 150,
    unlock_kind: "total_xp",
    unlock_threshold: 1000,
  },
  {
    id: "quarter-century",
    code: "quarter-century",
    name: "Quarter Century",
    description: "Complete twenty-five missions.",
    xp_bonus: 150,
    unlock_kind: "total_completions",
    unlock_threshold: 25,
  },
  {
    id: "half-century",
    code: "half-century",
    name: "Half Century",
    description: "Complete fifty missions.",
    xp_bonus: 250,
    unlock_kind: "total_completions",
    unlock_threshold: 50,
  },
  {
    id: "centurion",
    code: "centurion",
    name: "Centurion",
    description: "Complete one hundred missions.",
    xp_bonus: 500,
    unlock_kind: "total_completions",
    unlock_threshold: 100,
  },
  {
    id: "double-century",
    code: "double-century",
    name: "Double Century",
    description: "Complete two hundred missions.",
    xp_bonus: 750,
    unlock_kind: "total_completions",
    unlock_threshold: 200,
  },
  {
    id: "mission-master",
    code: "mission-master",
    name: "Mission Master",
    description: "Complete five hundred missions.",
    xp_bonus: 1500,
    unlock_kind: "total_completions",
    unlock_threshold: 500,
  },
  {
    id: "week-warrior",
    code: "week-warrior",
    name: "Week Warrior",
    description: "Log wins seven days in a row.",
    xp_bonus: 200,
    unlock_kind: "current_streak",
    unlock_threshold: 7,
  },
  {
    id: "fortnight-focus",
    code: "fortnight-focus",
    name: "Fortnight Focus",
    description: "Log wins fourteen days in a row.",
    xp_bonus: 350,
    unlock_kind: "current_streak",
    unlock_threshold: 14,
  },
  {
    id: "monthly-momentum",
    code: "monthly-momentum",
    name: "Monthly Momentum",
    description: "Log wins thirty days in a row.",
    xp_bonus: 600,
    unlock_kind: "current_streak",
    unlock_threshold: 30,
  },
  {
    id: "unbroken-fifty",
    code: "unbroken-fifty",
    name: "Unbroken",
    description: "Log wins fifty days in a row.",
    xp_bonus: 1000,
    unlock_kind: "current_streak",
    unlock_threshold: 50,
  },
  {
    id: "centennial-streak",
    code: "centennial-streak",
    name: "Centennial Streak",
    description: "Log wins one hundred days in a row.",
    xp_bonus: 2000,
    unlock_kind: "current_streak",
    unlock_threshold: 100,
  },
  {
    id: "first-critical",
    code: "first-critical",
    name: "Under Pressure",
    description: "Complete your first critical mission.",
    xp_bonus: 50,
    unlock_kind: "critical_completed",
    unlock_threshold: 1,
  },
  {
    id: "critical-ten",
    code: "critical-ten",
    name: "Crisis Manager",
    description: "Complete ten critical missions.",
    xp_bonus: 200,
    unlock_kind: "critical_completed",
    unlock_threshold: 10,
  },
  {
    id: "critical-twenty-five",
    code: "critical-twenty-five",
    name: "Firefighter",
    description: "Complete twenty-five critical missions.",
    xp_bonus: 400,
    unlock_kind: "critical_completed",
    unlock_threshold: 25,
  },
  {
    id: "critical-fifty",
    code: "critical-fifty",
    name: "High-Stakes Veteran",
    description: "Complete fifty critical missions.",
    xp_bonus: 750,
    unlock_kind: "critical_completed",
    unlock_threshold: 50,
  },
  {
    id: "critical-hundred",
    code: "critical-hundred",
    name: "Pressure Cooker",
    description: "Complete one hundred critical missions.",
    xp_bonus: 1500,
    unlock_kind: "critical_completed",
    unlock_threshold: 100,
  },
  {
    id: "xp-500",
    code: "xp-500",
    name: "Getting Started",
    description: "Earn 500 XP.",
    xp_bonus: 75,
    unlock_kind: "total_xp",
    unlock_threshold: 500,
  },
  {
    id: "xp-2500",
    code: "xp-2500",
    name: "XP Collector",
    description: "Earn 2,500 XP.",
    xp_bonus: 250,
    unlock_kind: "total_xp",
    unlock_threshold: 2500,
  },
  {
    id: "xp-5000",
    code: "xp-5000",
    name: "XP Hoarder",
    description: "Earn 5,000 XP.",
    xp_bonus: 500,
    unlock_kind: "total_xp",
    unlock_threshold: 5000,
  },
  {
    id: "xp-10000",
    code: "xp-10000",
    name: "Five Figures",
    description: "Earn 10,000 XP.",
    xp_bonus: 1000,
    unlock_kind: "total_xp",
    unlock_threshold: 10000,
  },
  {
    id: "xp-25000",
    code: "xp-25000",
    name: "XP Magnate",
    description: "Earn 25,000 XP.",
    xp_bonus: 2500,
    unlock_kind: "total_xp",
    unlock_threshold: 25000,
  },
  {
    id: "xp-50000",
    code: "xp-50000",
    name: "Legendary Grind",
    description: "Earn 50,000 XP.",
    xp_bonus: 5000,
    unlock_kind: "total_xp",
    unlock_threshold: 50000,
  },
  {
    id: "completions-fifteen",
    code: "completions-fifteen",
    name: "Fifteen Strong",
    description: "Complete fifteen missions.",
    xp_bonus: 100,
    unlock_kind: "total_completions",
    unlock_threshold: 15,
  },
  {
    id: "streak-five",
    code: "streak-five",
    name: "Five Alive",
    description: "Log wins five days in a row.",
    xp_bonus: 150,
    unlock_kind: "current_streak",
    unlock_threshold: 5,
  },
  {
    id: "streak-twenty-one",
    code: "streak-twenty-one",
    name: "Habit Formed",
    description: "Log wins twenty-one days in a row.",
    xp_bonus: 500,
    unlock_kind: "current_streak",
    unlock_threshold: 21,
  },
  {
    id: "critical-five-hundred",
    code: "critical-five-hundred",
    name: "Crisis Legend",
    description: "Complete five hundred critical missions.",
    xp_bonus: 3000,
    unlock_kind: "critical_completed",
    unlock_threshold: 500,
  },
];

export const demoProfile: Profile = {
  id: demoUserId,
  display_name: "Parker",
  avatar_initials: "P",
  total_xp: 385,
  level: 2,
  current_streak: 2,
  longest_streak: 4,
};

export const demoTasks: Task[] = [
  {
    id: "task-reset-kitchen",
    user_id: demoUserId,
    category_id: "home-base",
    title: "Reset kitchen and clear counters",
    notes: "Fast cleanup before the evening shutdown.",
    status: "pending",
    priority: "medium",
    due_at: today.toISOString(),
    scheduled_for: today.toISOString().slice(0, 10),
    xp_value: 35,
  },
  {
    id: "task-career-block",
    user_id: demoUserId,
    category_id: "career-forge",
    title: "Ship one focused portfolio improvement",
    notes: "Pick the smallest visible improvement and finish it.",
    status: "pending",
    priority: "high",
    due_at: tomorrow.toISOString(),
    scheduled_for: tomorrow.toISOString().slice(0, 10),
    xp_value: 60,
  },
  {
    id: "task-admin",
    user_id: demoUserId,
    category_id: "command-center",
    title: "Review bills and calendar",
    notes: "Close loops before they become noise.",
    status: "pending",
    priority: "critical",
    due_at: yesterday.toISOString(),
    scheduled_for: yesterday.toISOString().slice(0, 10),
    xp_value: 75,
  },
];

export const demoHabits: Habit[] = [
  {
    id: "habit-training",
    user_id: demoUserId,
    category_id: "body",
    title: "Training session",
    cadence: "daily",
    xp_value: 45,
    active: true,
    last_completed_at: yesterday.toISOString(),
  },
  {
    id: "habit-study",
    user_id: demoUserId,
    category_id: "skills",
    title: "Thirty minutes of learning",
    cadence: "daily",
    xp_value: 30,
    active: true,
    last_completed_at: null,
  },
];

export const demoCompletions: TaskCompletion[] = [
  {
    id: "completion-1",
    user_id: demoUserId,
    task_id: null,
    habit_id: "habit-training",
    completed_at: today.toISOString(),
    xp_awarded: 45,
  },
  {
    id: "completion-2",
    user_id: demoUserId,
    task_id: "task-old",
    habit_id: null,
    completed_at: yesterday.toISOString(),
    xp_awarded: 40,
  },
];

export const demoXpEvents: XpEvent[] = [
  {
    id: "xp-1",
    user_id: demoUserId,
    source_type: "habit",
    source_id: "habit-training",
    points: 45,
    description: "Completed Training session",
    created_at: today.toISOString(),
  },
  {
    id: "xp-2",
    user_id: demoUserId,
    source_type: "task",
    source_id: "task-old",
    points: 40,
    description: "Completed weekly review",
    created_at: yesterday.toISOString(),
  },
];
